### ISSUE TITLE
Predict_proba no attribute

### ISSUE THREAD

**Issue by acheaito97** [vardanagarwal/Proctoring-AI#11]
i got this error :
prob = clf.predict_proba(feature_vector)[0][1]
AttributeError: 'str' object has no attribute 'predict_proba'

**Comment by acheaito97** [comment]
@vardanagarwal

**Comment by vardanagarwal** [comment]
I am guessing you are getting this error in the face spoofing program. Can you make sure your model is being correctly loaded and you have the correct version of scikit learn as mentioned in README, because the model is incompatible with newer versions.

**Comment by acheaito97** [comment]
after using the same version of scikit learn i got this extra error :

> **DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
>   from collections import Sequence
> Traceback (most recent call last):
>   File "Proctoring-AI-master/face_spoofing.py", line 55, in <module>
>     prediction = clf.predict_proba(feature_vector)
> AttributeError: 'str' object has no attribute 'predict_proba'
> [ WARN:0] global ..\modules\videoio\src\cap_msmf.cpp (435) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback**

**Comment by acheaito97** [comment]
the problem is solved 
thank you
