### ISSUE TITLE
TypeError: 'Tensor' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by kshamap** [vardanagarwal/Proctoring-AI#12]
Hi,
While running person_and_phone.py I am getting following issue.

Traceback (most recent call last):
  File "person_and_phone.py", line 342, in <module>
    for i in range(nums[0]):
TypeError: 'Tensor' object cannot be interpreted as an integer

Need Help.

**Comment by vardanagarwal** [comment]
Can you make sure your Tf version>2.

**Comment by kshamap** [comment]
yes you are right. I update TF version.
Thanks for the fast reply.

It worked thanks a lot.
