### ISSUE TITLE
Web App compatibility

### ISSUE THREAD

**Issue by Pavan-Kumar122** [vardanagarwal/Proctoring-AI#13]
Will your project be implemented on web app's, like in any exam portal??

**Comment by vardanagarwal** [comment]
I don't plan to do that myself. If you want to build that you can and start a pull request.

**Comment by Pavan-Kumar122** [comment]
yeah i've been working on my college project so for that, i'm encountering some problem while doing face detection.

**Comment by Pavan-Kumar122** [comment]
actually do you have any idea about how we can implement face detection , so that any user who open the portal the camera will also get accessed and face detection will also done

**Comment by vardanagarwal** [comment]
No, sorry.
