### ISSUE TITLE
from sklearn.externals import joblib -  face_spoofing.py

### ISSUE THREAD

**Issue by naushadck** [vardanagarwal/Proctoring-AI#15]
There is one difficulty in using this module. System throws an error from line # 3. 

Seems that the joblib name is not available under scikit-learn module.
If using joblib or pickle module, throws an error while opening the  face_spoofing.pkl. 
Seems that both modules internally uses the scikit-learn.externals.joblib to open the file. 

How can be resolved this....

**Comment by vardanagarwal** [comment]
Please check your sklearn version. The model I found used sklearn 0.19.1 and does not work with newer versions.

**Comment by naushadck** [comment]
Thanks for your quick reply. 

I am able to run face_spoofing.py.   Result is not accurate.  For real face, some times it says "True" sometimes it says "False"
For photo/pictures as well. 

Any updated model.....

**Comment by vardanagarwal** [comment]
Yes I know that. It is added as a to do in the Readme. I was working on a deadline initially to make this project for a college course and the datasets need a form, hence I did not train one and used the easiest one I got.

Maybe there might be some open sourced models available on GitHub with which it can be replaced which utilize deep learning libraries.
