### ISSUE TITLE
On screen coordinates

### ISSUE THREAD

**Issue by santosh9sanjeev** [vardanagarwal/Proctoring-AI#16]
Hi I am actually working on a similar project..
Suppose I am opening another video on a full size frame with the gaze running in the background..
I am trying to plot the points where the person is looking at on the full size frame...
In simple terms I am trying to plot the points where the person is looking in the screen 
Any idea how to solve this problem, it would be very helpful

**Comment by vardanagarwal** [comment]
I am sorry, I have never tried to perform this, so I don't have any ideas. However, there must surely be some implementations of it on GitHub. It is not relevant to this project, hence I am closing this issue.
