### ISSUE TITLE
Main.py missing

### ISSUE THREAD

**Issue by Praveen-Nerhethil** [vardanagarwal/Proctoring-AI#17]
Please help us to get the combined python file

**Comment by vardanagarwal** [comment]
Please have a look at the other branch. That has the combined file. However, there are only eye tracking, mouth opening detection an person detection implemented in it.

It is not developed in the new branch as running those things together was very slow with multithreading. So adding further functionalities will be even slower. You can get a rough idea from that if you you want to develop it.

**Comment by vardanagarwal** [comment]
https://github.com/vardanagarwal/Proctoring-AI/blob/old_master/main.py
