### ISSUE TITLE
Where are all the data files?

### ISSUE THREAD

**Issue by anjali-ramesh** [vardanagarwal/Proctoring-AI#2]
Can you please commit all the data files that you used? Thank you.

**Comment by vardanagarwal** [comment]
Could you please elaborate which data files you are looking for? 

No seperate data has been used to train the models as only pre-trained models were used. If you are looking for pre-trained models then:

YoloV3 - You can uncomment the wget in the code or download from here https://pjreddie.com/darknet/yolo/

Dlib Key points - http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2
