### ISSUE TITLE
Audio code error

### ISSUE THREAD

**Issue by Praveen-Nerhethil** [vardanagarwal/Proctoring-AI#21]
Traceback (most recent call last):
  File "audio_part.py", line 84, in <module>
    convert(i);
  File "audio_part.py", line 37, in convert
    with sr.AudioFilesound as source:
AttributeError: module 'speech_recognition' has no attribute 'AudioFilesound'

**Comment by vardanagarwal** [comment]
The problem has to be with your installation as it is an inbuilt library.  The version I used of speech_recognition library is 3.6.3, so if your installation is correct you can maybe try with this version.
