### ISSUE TITLE
detect_marks() not working

### ISSUE THREAD

**Issue by Jawkx** [vardanagarwal/Proctoring-AI#22]
Hi, I tried your code and I copied your save_model.pb file. I use my own face detection algorithm and plan to use your face landmark system. The detect_marks() is not working and it shows the error ` got shape [1, 128, 128, 3], but wanted [1] `. Do you know what should I do to fix this ?

Thank you very much

**Comment by vardanagarwal** [comment]
@Jawkx please have a look at the the function defination of the function detect_marks in the face_landmarks.py. You need to pass the original image along with [x0, y0, X1, y0] which represents the face box coordinates you would have found from face detector. it should work then.

**Comment by Jawkx** [comment]
Issue solved, thanks
