### ISSUE TITLE
Problem in person_and_phone

### ISSUE THREAD

**Issue by tannertidus** [vardanagarwal/Proctoring-AI#29]
Hi!

I'm using the instructions here "https://medium.com/analytics-vidhya/count-people-in-webcam-using-yolov3-tensorflow-f407679967d5". I'm using python3.7 and opencv 4. When I execute the script, I get:

Traceback (most recent call last):
  File "person_and_phone.py", line 337, in <module>
    for i in range(nums[0]):
TypeError: 'Tensor' object cannot be interpreted as an integer
[ WARN:0] global ..\modules\videoio\src\cap_msmf.cpp (435) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback

Any idea?

Thank you very match, you do a great job!!

**Comment by vardanagarwal** [comment]
Hi @tannertidus, can you make sure you are using Tensorflow 2.

**Comment by tannertidus** [comment]
Thank you! It was that, I had not realized :)
