### ISSUE TITLE
Error: Cannot import name 'nothing' from 'dlib_helper'

### ISSUE THREAD

**Issue by stu-ball** [vardanagarwal/Proctoring-AI#3]
I'm getting the following error:

Exception has occurred: ImportError
cannot import name 'nothing' from 'dlib_helper' (/Proctoring-AI/dlib_helper.py) 
File "/Proctoring-AI/main.py", line 13, in <module> 
from dlib_helper import (shape_to_np,

Please let me know if you need any additional details.

**Comment by vardanagarwal** [comment]
It is resolved.
