### ISSUE TITLE
i am stuck with a problem in your code please check and help me 

### ISSUE THREAD

**Issue by Praveen-Nerhethil** [vardanagarwal/Proctoring-AI#30]
load_darknet_weights(yolo, 'yolov3.weights')
  File "C:\Users\IOT\Downloads\Proctoring-AI-old_master\Proctoring-AI-old_master\yolo_helper.py", line 35, in load_darknet_weights
    wf = open(weights_file, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'yolov3.weights'

**Comment by vardanagarwal** [comment]
Please download the yolov3 weights file.

You could comment out line 323 `weights_download()` to download using wget in `person_and_person.py` in the current master branch or you could download from online and place it in the working directory.
