### ISSUE TITLE
To take video from client device to the server.

### ISSUE THREAD

**Issue by Praveen-Nerhethil** [vardanagarwal/Proctoring-AI#36]
Hi there,

    I am doing  proctoring project and I need help to obtain the live video feed from the client device to the server.  I was successful in hosting my video in localhost but now to proctor the exam, I need access to the live video feed of the candidates in my server. Can you help me in this?

**Comment by vardanagarwal** [comment]
Sorry, this is not my area of expertise and I won't be working on this. However, if you manage to do this I will be happy to merge it in this repo.
