### ISSUE TITLE
Is the pre-trained facial landmark model included?

### ISSUE THREAD

**Issue by shilezhang** [vardanagarwal/Proctoring-AI#37]
Hello 
When I run `python head_pose_estimation.py` I get the following error:
`OSError: Unable to open file (file read failed: time = Sun Dec 27 21:55:55 2020
, filename = 'models/pose_model', file descriptor = 3, errno = 21, error message = 'Is a directory', buf = 0x7fff051ef380, total read size = 8, bytes this sub-read = 8, bytes actually read = 18446744073709551615, offset = 0)
`
Is the pre-trained facial landmark model included in the folder? Or we need to train from the repo([https://github.com/yinguobing/facial-landmark-detection-hrnet](url) )you have offered.

**Comment by vardanagarwal** [comment]
There is a pose_model folder present in the models directory. You can use that or download the original one one the link you mentioned.
