### ISSUE TITLE
facing issue in loading facial landmark model

### ISSUE THREAD

**Issue by solutioninfinite** [vardanagarwal/Proctoring-AI#42]
ERROR:  
fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (file signature not found)

my model path is saved_model=os.getcwd()+'/models/pose_model/saved_model.pb'

code in which i am getting this error is  :   model = keras.models.load_model(saved_model)

Please help me, friends. I am new to computer vision.

I also tried to find the model in this link (https://github.com/yinguobing/cnn-facial-landmark) but I am not able to find any trained model is present in this repo.

**Comment by vardanagarwal** [comment]
You will find the the model in models folder.
