### ISSUE TITLE
re-training of face detector resnet model

### ISSUE THREAD

**Issue by pallpb** [vardanagarwal/Proctoring-AI#44]
Hi,
I want to re-train the OpenCV/DNN resnet10 model. 
I want to replace normalize layer from the model. As my hardware does not support it.
Is there any way I can replace normalize layer and re-train the model
I have followed the original tutorial from openCV 
[https://github.com/opencv/opencv/blob/master/samples/dnn/face_detector/how_to_train_face_detector.txt](url) 
only question is about replacing the layer 

Thanks.

**Comment by vardanagarwal** [comment]
Hi, I am sorry I dont know how to do it. I guess this question would be better served on StackOverflow.
