### ISSUE TITLE
Starting of project (Urgent)

### ISSUE THREAD

**Issue by HarshitaSahai** [vardanagarwal/Proctoring-AI#45]
Can anyone guide me regarding running the project?
I'm able to understand the file dependencies and relation but from where to start in running  /face_detection/faces_detection.py this would work or something else?

**Comment by vardanagarwal** [comment]
The face_detection/faces_detection is a sort of side project I had done to find the best face detector.

You just need to run any of the functionality which you want. The face_detector.py and face_landmarks.py act as helper functions.

**Comment by HarshitaSahai** [comment]
How can I run the functionality? Like running .py files doesn't work I tried as they are linked can you please guide?
Thank you
