### ISSUE TITLE
Does this library work with pre-recorded videos?

### ISSUE THREAD

**Issue by mirunamd** [vardanagarwal/Proctoring-AI#46]
I read through the documentation and based on my understanding the library works with live video feeds. I am interested to know if it can be passed a video file as input as well?

Thanks

**Comment by vardanagarwal** [comment]
Yes! It uses OpenCv for video capturing which can be used for both pre-recorded videos or live videos. Just change the 0 in `cv2.VideoCapture(0)` to the filename in quotes and it will work.

**Comment by mirunamd** [comment]
Thank you!

I tested it as you suggested (eye_tracker.py in particular). The video is playing back slower than the original - this is not an issue but was curious to see if it's just me. 

I don't see any of the outputs that I normally see with the livestream (e.g Looking up, down) in the console when using a pre-recorded video as the input. Can you please let me know if it's a bug or I am doing something wrong?
