### ISSUE TITLE
No module named 'sklearn.ensemble.forest'

### ISSUE THREAD

**Issue by Lal47** [vardanagarwal/Proctoring-AI#47]
Hi, while trying to run the code for face spoofing, I happen to encounter a No module named 'sklearn.ensemble.forest'.
Any idea why this is so?

**Comment by vardanagarwal** [comment]
Have you installed the correct version as given in the Readme?

**Comment by Lal47** [comment]
Okay I overlooked that. My bad, it's working now. Thank you
