### ISSUE TITLE
Issues with scikit-learn for face spoofing 

### ISSUE THREAD

**Issue by mirunamd** [vardanagarwal/Proctoring-AI#49]
Would it be possible to upgrade the dependency ```scikit-learn``` for the face spoofing module to the latest? I am having issues installing the one that's required (0.19.1) with pip install and can't find it in the [pypi repo](https://pypi.org/search/?q=scikit-learn-0.19.1). 

The builds for some older versions of ```scikit-learn``` are failing as well.

**Comment by vardanagarwal** [comment]
I used an off the shelf model which I could find. It is not trained by me nor do I have the access to that dataset to improve it. If you want you can train a model or find another working model and create a pull request.
