### ISSUE TITLE
Error in downloading dlib 

### ISSUE THREAD

**Issue by smane2000** [vardanagarwal/Proctoring-AI#5]
Hello vardhan... I'm having the issue to download dlib, tried various ways to install it but I'm not able to install it..so plz can u help me out to install dlib or the steps u followed to install dlib... Hope u will help me out to solve this.

**Comment by vardanagarwal** [comment]
Can you tell which os are you using and are you using Anaconda?

**Comment by smane2000** [comment]
Windows 10

**Comment by smane2000** [comment]
Windows

**Comment by vardanagarwal** [comment]
if you are going for pip install then you can follow this https://www.google.com/amp/s/www.learnopencv.com/install-dlib-on-windows/amp/. Hopefully it should work. 

If you are using Anaconda then you do:
conda install -c conda-forge dlib
If that doesn't work then go for:
conda install -c menpo dlib
However, the second command is only for python <= 3.5.

**Comment by smane2000** [comment]
It's not working..can u tell me how did u installed it

**Comment by smane2000** [comment]
Thanx for the solution but it's not working...

**Comment by vardanagarwal** [comment]
Which one did you try? I am personally working on Windows using Anaconda and it worked for me.

**Comment by smane2000** [comment]
Hello vardan Thanx for the solution.. It worked after 2 times of installing Becz there was a installation issues..

**Comment by AnanyaKukreti** [comment]
Hi Vardan, I'm working on windows and using Anaconda, but the command is not working for me. Do you need to install something else before using the command to make it work?
