### ISSUE TITLE
eye tracker not outputting anything (pre-recorded video)

### ISSUE THREAD

**Issue by mirunamd** [vardanagarwal/Proctoring-AI#50]
Follow-up from issue #46.

I tested the code as you suggested (eye_tracker.py in particular) with a pre-recorded video instead of a livestream. 

I don't see any of the outputs that I normally see with the livestream (e.g Looking up, down) in the console. Can you please let me know if it's a bug or I am doing something wrong?

Note: ```mouth_opening_detector.py``` and ```face_detector.py``` work and output the results to the console.

**Comment by vardanagarwal** [comment]
The threshold needs to be set otherwise the technique is not accurate. Otherwise it should not be a bug.

**Comment by mirunamd** [comment]
> The threshold needs to be set otherwise the technique is not accurate. Otherwise it should not be a bug.

Can you please give an example or be more specific? Thanks.
