### ISSUE TITLE
Library capabilities

### ISSUE THREAD

**Issue by mirunamd** [vardanagarwal/Proctoring-AI#51]
1. For the eye_tracker.py, is there no way to identify if a person is looking down? From what I see, the lib can only identify left, right or up eye movements.
2. For head_pose_estimation.py, is there no "neutral" head pose? For instance, when I am looking directly at the camera, the output keeps saying left.

**Comment by vardanagarwal** [comment]
1. No the eye tracker can't detect looking down as the movement of pupil with respect to the eye is minimal.
2. It should be neitral, but the model isn't pretty accurate. Maybe converting the two axis to roll, pitch and yaw may give better results or you can play around with the parameters and increase the threshold for left.

**Comment by GuruNadh552** [comment]
can you please send me the modules with version in detail for executing this in my system

**Comment by vardanagarwal** [comment]
@GuruNadh552 I am sorry, I didn't understand what you meant.

**Comment by GuruNadh552** [comment]
Can you please explain to me how to execute this project  and how to download the modules which are compatible to this project
