### ISSUE TITLE
Key Error : "predict" when trying to get the landmarks

### ISSUE THREAD

**Issue by ycherukury** [vardanagarwal/Proctoring-AI#52]
Hi i loaded the model from the same models folder, but when i run the model.signatures["predict"], it returns a key error. 
I have tried printing the model.signatures.keys(). There is no "predict" key in it. only dense_1 is there.

**Comment by vardanagarwal** [comment]
You can take a look at eye_tracker.py to see how to run the face landmarks file. Also make sure your tensoflow version is > 2 and <= 2.3.

**Comment by alvarobasi** [comment]
I'm experiencing the same issue with 2.4.1 and 2.3.0. I wasn't having this issue before, I don't know what has changed exactly...
