### ISSUE TITLE
RuntimeError: Unable to open shape_68.dat

### ISSUE THREAD

**Issue by manjunathgk029** [vardanagarwal/Proctoring-AI#54]
predictor = dlib.shape_predictor('shape_68.dat')
error is this line.
could you please help me to solve this issue?

<img width="427" alt="error" src="https://user-images.githubusercontent.com/50828129/115698981-d506ca00-a382-11eb-9ef7-721582e74a1e.png">

**Comment by vardanagarwal** [comment]
You need to download the dlib landmark detection model and rename it to shape_68. Then it will work.
