### ISSUE TITLE
Can you tell where is this file attached shape_68.dat

### ISSUE THREAD

**Issue by Goutham-source** [vardanagarwal/Proctoring-AI#58]
Traceback (most recent call last):
  File "E:/Eyeball open/eyetracknew.py", line 35, in <module>
    predictor = dlib.shape_predictor('shape_68.dat')
RuntimeError: Unable to open shape_68.dat

**Comment by vardanagarwal** [comment]
You can download from here: https://github.com/davisking/dlib-models/blob/master/shape_predictor_68_face_landmarks.dat.bz2

Rename it to shape_68.dat

**Comment by Goutham-source** [comment]
How to open this kind of file

Regards,
Goutham K
Technical Trainer
iObrain Innovative Labz <http://www.iobrain.in>
Address: #786/A, 1st Floor, 1st Cross, 7th Block, 2nd Phase, Banashankari
3rd Stage, Bengaluru, Karnataka 560085

**Comment by vardanagarwal** [comment]
It's a compression format. Uncompress it and use the dat file.
