### ISSUE TITLE
About .dat files

### ISSUE THREAD

**Issue by jayp84847** [vardanagarwal/Proctoring-AI#59]
Yet I am working on project where I am using dlib 68 face landmarks. But as tou know its not enough stable. So in some research I git many stable 68 face landmarks. 

But all of these based on python. So can you guide me how can we make ".dat" file from it. Or any suggestions about ".dat" file?

68 face landmarks stable module: https://github.com/facebookresearch/supervision-by-registration

98 face landmarks module: https://wywu.github.io/projects/LAB/WFLW.html

**Comment by vardanagarwal** [comment]
Sorry have no idea about that.
