### ISSUE TITLE
Unable to import dlib. Does dlib need a GPU compulsorily?

### ISSUE THREAD

**Issue by shubhampk37** [vardanagarwal/Proctoring-AI#66]
I'm using a Intel Pentium B960 Processor.
I'm unable to import dlib.
I think there's an issue of GPU and CUDA.
Can you please tell me how can I proceed further?

Anaconda Promt:
>>> import dlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\shubh\Anaconda3\envs\ET\lib\site-packages\dlib\__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: DLL load failed while importing _dlib_pybind11: A dynamic link library (DLL) initialization routine failed.

**Comment by vardanagarwal** [comment]
No that's not necessary.

**Comment by shubhampk37** [comment]
So how should I proceed with working on the code then if I'm unable to import dlib?

**Comment by vardanagarwal** [comment]
The main branch doesn't use dlib, instead uses a tensorflow model for the facial landmarks, you can use that.
