### ISSUE TITLE
Issue while loading shape_68.dat file

### ISSUE THREAD

**Issue by Praveen-Nerhethil** [vardanagarwal/Proctoring-AI#7]
`Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Traceback (most recent call last):
  File ".\main.py", line 24, in <module>
    predictor = dlib.shape_predictor('shape_68.dat')
RuntimeError: Error deserializing object of type int`

Hai @vardanagarwal ,
Can you please help me to solving the above error.

**Comment by vardanagarwal** [comment]
I faced the same issue and I had found this StackOverflow question: https://stackoverflow.com/questions/43981231/dlib-error-deserializing-object-of-type-short/50698230 which suggested to re-download the file and that worked.

P.S. - If you are looking for where to download it then open the link, it has a link to download the file.
