### ISSUE TITLE
Python and dependecies version

### ISSUE THREAD

**Issue by ppseverin** [vardanagarwal/Proctoring-AI#75]
Hi I was looking at the project dependencies and I wanted to know what was the python version used and if it is possible to do an upgrade on this repository or if there is any kind of restriction due to compatibility versions between packages.

I tried to run the scripts, but I found some "missing" dependencies, like `ModuleNotFoundError: No module named 'sklearn.ensemble.forest'`, for example.

Also, can or should this project run on windows? Or is intended to run on Linux.

**Comment by vardanagarwal** [comment]
I ran it on linux with python3.8, so can't comment whether windows will have issues. As for as the exact dependencies, you can refer to requirements.txt file.
