### ISSUE TITLE
Requesting Push Access to Proctoring-AI Repository

### ISSUE THREAD

**Issue by bhushankhopkarr** [vardanagarwal/Proctoring-AI#76]
i want to add the yolov3.weights file and also make some changes into it .

**Comment by vardanagarwal** [comment]
you can create a pr and i'll review and accept it if I feel it adds to the code. I don't want to add the weights file to the repository and unnecessarily increase the size.

**Comment by bhushankhopkarr** [comment]
okayyy sure thank you!!
