### ISSUE TITLE
What does this line do? what does p1, p2, and m stand for? 

### ISSUE THREAD

**Issue by 0xinit** [vardanagarwal/Proctoring-AI#8]
It is very unclear what [this](https://github.com/vardanagarwal/Proctoring-AI/blob/a4616d0818daaa34a29c72914abc4e9c5610db56/head_pose_estimation.py#L189) line does. Can you tell me what are p1, p2, m are? Why have we used that formula to calculate m? 

What about your yaw, roll and pitch?

**Comment by vardanagarwal** [comment]
p1 and p2 are the starting and ending points of the line used to estimate pose for up and down movement. p1 is actually the nose facial keypoint while p2 is the 3d point calculated which is projected in 2d space. m is the slope of a line that would be drawn between those points.

The code does not calculate in terms of yaw, roll and pitch. Instead, it is made with respect to monitoring a student while he/she is giving an online exam and reports whether they looking left, right, up or down and possibly at something to gain an unfair advantage in the exam.
